### ISSUE TITLE
line chart

### ISSUE THREAD

**Issue by joeshub** [AnSavvides/d3act#23]
This is great! Any ideas on how to implement a line chart?

**Comment by AnSavvides** [comment]
Hey!

Have a look at the [`SomeCustomChart` example](https://github.com/AnSavvides/d3act/blob/master/examples/app.jsx#L172-222) - you can take a similar approach to bring a line chart in, such as [this simple implementation from Mike Bostock](https://bl.ocks.org/mbostock/3883245).

**Comment by AnSavvides** [comment]
I am going to assume that this answered your question - let me know if there is anything else I can help you with :)
