### ISSUE TITLE
Upgrade to d3 4.x

### ISSUE THREAD

**Issue by jfsiii** [AnSavvides/d3act#24]
As of [v4](https://github.com/d3/d3/releases/tag/v4.0.0), d3 has been broken up into many modules (e.g. [`d3-scale`](https://github.com/d3/d3-scale), [`d3-selection`](https://github.com/d3/d3-selection), etc). There are also some [API changes](https://github.com/d3/d3/blob/master/CHANGES.md).

Not only is it a good idea to stay on the current major version, but the final size would drop quite a bit if `d3act` only imports the `d3` packages it needs.

I've ported a few examples and projects from 3.x to 4.x and it's relatively simple. Changing `import d3 from "d3"` to `import * as d3 from 'd3'` then doing a search-and-replace for the new methods names (old: `d3.scale.ordinal` new: `d3.scaleOrdinal`, etc) will get you pretty far. Converting to statements like `import { scaleLinear, scaleOrdinal } from 'd3-scale'` should be the ultimate goal, but I typically save that for a second pass after things are converted and working.

The [changes to selections](https://github.com/d3/d3/blob/master/CHANGES.md#selections-d3-selection) are probably the most substantial but, in my experience, don't take much effort to convert.

**Comment by AnSavvides** [comment]
Thanks for this @jfsiii, really appreciate you taking the time!

If you've got time, would you like to have a go at these changes yourself? If not, I'll try find time myself and work on this whenever I get a chance :)

**Comment by davidkui** [comment]
I have  a question. Does this version support the Tree graph?
thanks

**Comment by AnSavvides** [comment]
I can't tell you off the top of my head, but do have a look at the [d3 releases](https://github.com/d3/d3/releases) - `d3act` currently uses `v3.5.5` of `d3` :)

**Comment by cdotta** [comment]
I created a pull request to fit this issue

**Comment by AnSavvides** [comment]
Done as part of #26 - thanks @cdotta for working on this! 😄
